trigger:
  batch: true
  branches:
    include:
    - develop
    - staging
    - master
    - ops/*
  paths:
    exclude:
    -  docs/*
pr: none
resources:
  - repo: self

variables:
  # ========================================================================
  #                          Mandatory variables 
  # ========================================================================
  Docker.filePath: "**/docker/Dockerfile.local"
  Docker.app_repository: "flexregister"
  Docker.registry: "ICTD-HOPE-DEV-ACR"
  Docker.repository: "uniappsk8shopedev"
  Docker.url: "uniappsakshopedev.azurecr.io"

stages:
  - stage: build_and_push
    displayName: BUILD and PUSH
    jobs:
      - job: build_push_backend
        pool:
          vmImage: ubuntu-latest
        displayName: "[APP]"
        steps:
          - script: "docker pull $(Docker.url)/$(Docker.repository):latest"
            displayName: Pull latest for layer caching
            continueOnError: true # for first build, no cache

          - task: Docker@2
            displayName: Build
            inputs:
              command: build
              buildContext: "**/.."
              dockerfile: $(Docker.filePath)
              repository: $(Docker.app_repository)
              containerRegistry: $(Docker.registry)
              arguments: '--cache-from=$(Docker.url)/$(Docker.repository):latest'
              tags: |
                $(Build.BuildId)
                $(Build.SourceVersion)
                latest
          - task: Docker@2
            displayName: Push
            inputs:
              command: push
              repository: $(Docker.app_repository)
              containerRegistry: $(Docker.registry)
              arguments: '--cache-from=$(Docker.url)/$(Docker.repository):latest'
              tags: |
                $(Build.BuildId)
                $(Build.SourceVersion)
                latest